"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { footerData } from '@/lib/data';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function AIDisclosure() {
    return (
        <main className="min-h-screen bg-white text-gray-950 py-32 px-4">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="inline-flex items-center text-sm font-bold uppercase tracking-widest text-gray-500 hover:text-gray-950 transition-colors mb-12 group">
                    <ArrowLeft className="mr-2 w-4 h-4 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>

                <motion.h1
                    className="text-5xl md:text-6xl font-black uppercase tracking-tight mb-8"
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                >
                    {footerData.legal.aiDisclosure.title}
                </motion.h1>

                <div className="prose prose-lg prose-gray">
                    <p className="text-xl text-gray-600 mb-12 leading-relaxed">
                        {footerData.legal.aiDisclosure.content}
                    </p>

                    <h2 className="text-2xl font-bold mb-4">Our Commitment to Responsible AI</h2>
                    <p className="mb-6">
                        As an AI-powered consultancy, we leverage cutting-edge technology to provide our clients with a competitive edge. However, we believe that AI is a tool to augment human intelligence, not replace it.
                    </p>

                    <h3 className="text-xl font-bold mb-3">1. Human Review</h3>
                    <p className="mb-6">
                        Every insight, campaign optimization, and strategic recommendation generated by our AI systems is reviewed and validated by our expert marketing team before being presented to you or implemented.
                    </p>

                    <h3 className="text-xl font-bold mb-3">2. Data Privacy</h3>
                    <p className="mb-6">
                        Your proprietary business data is never used to train public or shared AI models. We use secure, private instances of AI tools to ensure your information remains yours.
                    </p>

                    <h3 className="text-xl font-bold mb-3">3. Continuous Monitoring</h3>
                    <p className="mb-6">
                        We continuously monitor the performance of our AI tools to ensure accuracy, fairness, and alignment with your specific brand values and goals.
                    </p>
                </div>
            </div>
        </main>
    );
}
